### PR TITLE
add channel-data question sql

### PR DESCRIPTION
**Pull request by mlippert**
## Description
Add a sql file with the sql query used for the metabase question.

This provides an example for doing the same thing for all metabase questions

## Motivation and context
The SQL queries used for the various analyses should be versioned in a diff'able fashion.

In addtion these queries can be used to setup Metabase for running these analyses from scratch which we should eventually have instructions on how to do.

## How has this been tested?
No testing has been done.

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**

### CODE REVIEW

**Comment by mlippert** [comment]
@brecriffs If you want to do this now, you could add commits with SQL files for the other questions you've created in metabase.

**Comment by brecriffs** [comment]
> @brecriffs If you want to do this now, you could add commits with SQL files for the other questions you've created in metabase.

Okay will do. I assume you will want similar headers for each query as well. So I will do my best to summarise each query, as you have done here.

**Comment by mlippert** [comment]
Great, thanks, and yes I would like similar headers for each query.

You might be able to add even more info about the purpose/usefulness of the query than I did.

**Review by brecriffs — APPROVED** [review]
Your documentation looks good. I added a little more information related to filtering by date.

**Comment by brecriffs** [comment]
@mlippert Added all sql queries, including a new one for the network graph raw data. How do you suggest I commit the new metabase.db.mv.db file which includes the network graph question, a new branch and PR?

**Review by mlippert — COMMENTED** [review]
Looks really good.
I wouldn't even have noticed (because my review didn't include verifying that the sql files match what's in the metabase DB) but I think you got a little ahead of yourself here, by adding sql for questions that aren't in the metabase DB yet.
I only noticed that sql file because you asked about updating the metabase DB  w/ that question in it.

In answer to your question, yes create a separate PR for that update. I'd say that any update to the metabase DB should also include matching updated (or new) sql question files, so normally the new sql file for the network graph question would be included in the commit with the updated metabase DB. But that's just notes for future changes. As I said this looks great, and the comments, including the inline ones will be super helpful for anyone who looks at them later.

**Comment by mlippert** [comment]
I'd approve this PR, but since I'm the one who opened it, it seems I can't.

My force push was only to edit your commit message summary @brecriffs (The body was good).
From `Commit all sql queries from metabase` to `Add sql files for all questions currently in the metabase db`

 There's no need to say you're committing something in a commit message

**Pull request merged**
